del StructWithinStructInlineInitializationMethod_03.obj

del StructWithinStructInlineInitializationMethod_03.exe

cl.exe /c /EHsc StructWithinStructInlineInitializationMethod_03.c

link.exe StructWithinStructInlineInitializationMethod_03.obj

StructWithinStructInlineInitializationMethod_03.exe
