del InlineInitializationWithLoopsDisplay.obj
del InlineInitializationWithLoopsDisplay.exe

cl.exe /c /EHsc InlineInitializationWithLoopsDisplay.c

link.exe InlineInitializationWithLoopsDisplay.obj

InlineInitializationWithLoopsDisplay.exe
