del SignificanceOfParameterizedReturnValue.obj

del SignificanceOfParameterizedReturnValue.exe

cl.exe /c /EHsc SignificanceOfParameterizedReturnValue.c

link.exe SignificanceOfParameterizedReturnValue.obj

SignificanceOfParameterizedReturnValue.exe
