del MultipleStructVariablesDeclarationMethod_03.obj

del MultipleStructVariablesDeclarationMethod_03.exe

cl.exe /c /EHsc MultipleStructVariablesDeclarationMethod_03.c

link.exe MultipleStructVariablesDeclarationMethod_03.obj

MultipleStructVariablesDeclarationMethod_03.exe
