del SingleStructVariableDeclarationMethod_04.obj

del SingleStructVariableDeclarationMethod_04.exe

cl.exe /c /EHsc SingleStructVariableDeclarationMethod_04.c

link.exe SingleStructVariableDeclarationMethod_04.obj

SingleStructVariableDeclarationMethod_04.exe
