del SingleStructVariableInlineInitialization.obj

del SingleStructVariableInlineInitialization.exe

cl.exe /c /EHsc SingleStructVariableInlineInitialization.c

link.exe SingleStructVariableInlineInitialization.obj

SingleStructVariableInlineInitialization.exe
