del SingleStructVariableDeclarationMethod_02.obj

del SingleStructVariableDeclarationMethod_02.exe

cl.exe /c /EHsc SingleStructVariableDeclarationMethod_02.c

link.exe SingleStructVariableDeclarationMethod_02.obj

SingleStructVariableDeclarationMethod_02.exe
