del StructWithinStructInlineInitializationMethod_02.obj

del StructWithinStructInlineInitializationMethod_02.exe

cl.exe /c /EHsc StructWithinStructInlineInitializationMethod_02.c

link.exe StructWithinStructInlineInitializationMethod_02.obj

StructWithinStructInlineInitializationMethod_02.exe
