del StructWithinStructDeclarationMethod_01.obj

del StructWithinStructDeclarationMethod_01.exe

cl.exe /c /EHsc StructWithinStructDeclarationMethod_01.c

link.exe StructWithinStructDeclarationMethod_01.obj

StructWithinStructDeclarationMethod_01.exe
