del SingleStructVariableDeclarationMethod_03.obj

del SingleStructVariableDeclarationMethod_03.exe

cl.exe /c /EHsc SingleStructVariableDeclarationMethod_03.c

link.exe SingleStructVariableDeclarationMethod_03.obj

SingleStructVariableDeclarationMethod_03.exe
