del StructWithinStructInlineInitializationMethod_04.obj

del StructWithinStructInlineInitializationMethod_04.exe

cl.exe /c /EHsc StructWithinStructInlineInitializationMethod_04.c

link.exe StructWithinStructInlineInitializationMethod_04.obj

StructWithinStructInlineInitializationMethod_04.exe
