del TheFiveArithmeticOperatorsAndAssignmentOperator.obj
del TheFiveArithmeticOperatorsAndAssignmentOperator.exe
cl.exe /c /EHsc TheFiveArithmeticOperatorsAndAssignmentOperator.c

link.exe TheFiveArithmeticOperatorsAndAssignmentOperator.obj

TheFiveArithmeticOperatorsAndAssignmentOperator.exe
