del StructWithinStructDeclarationMethod_04.obj

del StructWithinStructDeclarationMethod_04.exe

cl.exe /c /EHsc StructWithinStructDeclarationMethod_04.c

link.exe StructWithinStructDeclarationMethod_04.obj

StructWithinStructDeclarationMethod_04.exe
