del InlineInitializationWithPieceMealDisplay.obj
del InlineInitializationWithPieceMealDisplay.exe

cl.exe /c /EHsc InlineInitializationWithPieceMealDisplay.c

link.exe InlineInitializationWithPieceMealDisplay.obj

InlineInitializationWithPieceMealDisplay.exe
