del StructWithinStructDeclarationMethod_03.obj

del StructWithinStructDeclarationMethod_03.exe

cl.exe /c /EHsc StructWithinStructDeclarationMethod_03.c

link.exe StructWithinStructDeclarationMethod_03.obj

StructWithinStructDeclarationMethod_03.exe
