del CharacterRecognition_IfElse_And_IfElseIfLadder.obj
del CharacterRecognition_IfElse_And_IfElseIfLadder.exe

cl.exe /c /EHsc CharacterRecognition_IfElse_And_IfElseIfLadder.c

link.exe CharacterRecognition_IfElse_And_IfElseIfLadder.obj

CharacterRecognition_IfElse_And_IfElseIfLadder.exe
